{% set name = "wannierberri" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stepan-tsirkin/wannier-berri/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2fce963404bf8c584b2663877ce7ed239cf0f82b740ba15103f9060e330352e2
  patches:
    - init.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - scipy
    - lazy-property
    - pyfftw
    - colorama
    - termcolor
    - pyfiglet
  run:
    - python >=3.6
    - numpy
    - scipy
    - lazy-property
    - colorama
    - termcolor
    - pyfiglet
    - pyfftw
    - fortio
    - packaging
    - numba
    - matplotlib-base
    - ray-core
    - spglib

test:
  imports:
    - wannierberri
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://wannier-berri.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Advanced tool for Wannier interpolation and integration of k-space integrals

  description: |
    Evaluation of k-space integrals of Berry curvature, orbital moment and 
    derived quantities by means of MLWFs or tight-binding models. Compared 
    to postw90.x part of Wannier90 code, it has extended functional and 
    improved performance
  doc_url: http://wannier-berri.org
  dev_url: https://github.com/stepan-tsirkin/wannier-berri

extra:
  recipe-maintainers:
    - jan-janssen
