{% set name = "wannierberri" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4048e0e5e3e7b33b2eb06ebf89dc8c0a362f50b5cfd5d094e4c0dbd8fc02f58e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - scipy >=1.13
    - colorama
    - termcolor
    - numba >=0.55.2
    - packaging >=20.8
    - fortio >=0.4
    - wannier90io
    - irrep
    - sympy

test:
  imports:
    - wannierberri
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://wannier-berri.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Advanced tool for Wannier interpolation and integration of k-space integrals

  description: |
    Evaluation of k-space integrals of Berry curvature, orbital moment and 
    derived quantities by means of MLWFs or tight-binding models. Compared 
    to postw90.x part of Wannier90 code, it has extended functional and 
    improved performance
  doc_url: http://wannier-berri.org
  dev_url: https://github.com/stepan-tsirkin/wannier-berri

extra:
  recipe-maintainers:
    - jan-janssen
