{% set name = "wannierberri" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a5cb436d2664ce06c153c214f8f13b6647242632724f5fd151a283d36bb8af2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy <1.25,>=1.24
    - scipy >=1.0
    - colorama
    - termcolor
    - numba >=0.55.2
    - packaging >=20.8
    - fortio >=0.4
    - wannier90io
    - irrep
    - sympy

test:
  imports:
    - wannierberri
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://wannier-berri.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Advanced tool for Wannier interpolation and integration of k-space integrals

  description: |
    Evaluation of k-space integrals of Berry curvature, orbital moment and 
    derived quantities by means of MLWFs or tight-binding models. Compared 
    to postw90.x part of Wannier90 code, it has extended functional and 
    improved performance
  doc_url: http://wannier-berri.org
  dev_url: https://github.com/stepan-tsirkin/wannier-berri

extra:
  recipe-maintainers:
    - jan-janssen
